<?php
/**
 * Generated by tools/refactor/build-class-map.php. Do not edit by hand.
 *
 * Timestamp: 2026-04-23T13:07:40+00:00
 * Entries:   73
 *
 * @package DoubleScale\Pro\Pro
 */

return array (
  'DoubleScale\\Pro\\Pro\\Logger' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\Logger\\Logger',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Logger.php',
    'new_path' => 'includes/Core/Logger/Logger.php',
  ),
  'DoubleScale\\Pro\\Pro\\Modules\\Automations\\AbandonedCart\\AbandonedCart' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Modules\\Automations\\AbandonedCart\\AbandonedCart',
    'module' => 'automations',
    'public' => false,
    'old_path' => 'includes/Modules/Automations/AbandonedCart/AbandonedCart.php',
    'new_path' => 'includes/Modules/Automations/AbandonedCart/AbandonedCart.php',
  ),
  'DoubleScale\\Pro\\Pro\\Modules\\Automations\\Rest\\Controllers\\RestAbandonedCartController' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Modules\\Automations\\Rest\\Controllers\\RestAbandonedCartController',
    'module' => 'automations',
    'public' => false,
    'old_path' => 'includes/Modules/Automations/Rest/Controllers/RestAbandonedCartController.php',
    'new_path' => 'includes/Modules/Automations/Rest/Controllers/RestAbandonedCartController.php',
  ),
  'DoubleScale\\Pro\\Pro\\Modules\\Automations\\Models\\AbandonedCartModel' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Modules\\Automations\\Models\\AbandonedCartModel',
    'module' => 'automations',
    'public' => false,
    'old_path' => 'includes/Modules/Automations/Models/AbandonedCartModel.php',
    'new_path' => 'includes/Modules/Automations/Models/AbandonedCartModel.php',
  ),
  'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartShippingFirstName' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartShippingFirstName',
    'module' => 'automations',
    'public' => false,
    'old_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartShippingFirstName.php',
    'new_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartShippingFirstName.php',
  ),
  'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartShippingCompany' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartShippingCompany',
    'module' => 'automations',
    'public' => false,
    'old_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartShippingCompany.php',
    'new_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartShippingCompany.php',
  ),
  'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartTotal' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartTotal',
    'module' => 'automations',
    'public' => false,
    'old_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartTotal.php',
    'new_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartTotal.php',
  ),
  'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartBillingPostCode' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartBillingPostCode',
    'module' => 'automations',
    'public' => false,
    'old_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartBillingPostCode.php',
    'new_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartBillingPostCode.php',
  ),
  'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartBillingLastName' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartBillingLastName',
    'module' => 'automations',
    'public' => false,
    'old_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartBillingLastName.php',
    'new_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartBillingLastName.php',
  ),
  'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartBillingCompany' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartBillingCompany',
    'module' => 'automations',
    'public' => false,
    'old_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartBillingCompany.php',
    'new_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartBillingCompany.php',
  ),
  'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartBillingAddress1' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartBillingAddress1',
    'module' => 'automations',
    'public' => false,
    'old_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartBillingAddress1.php',
    'new_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartBillingAddress1.php',
  ),
  'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartBillingState' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartBillingState',
    'module' => 'automations',
    'public' => false,
    'old_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartBillingState.php',
    'new_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartBillingState.php',
  ),
  'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartBillingAddress2' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartBillingAddress2',
    'module' => 'automations',
    'public' => false,
    'old_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartBillingAddress2.php',
    'new_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartBillingAddress2.php',
  ),
  'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartShippingPostCode' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartShippingPostCode',
    'module' => 'automations',
    'public' => false,
    'old_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartShippingPostCode.php',
    'new_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartShippingPostCode.php',
  ),
  'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartShippingLastName' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartShippingLastName',
    'module' => 'automations',
    'public' => false,
    'old_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartShippingLastName.php',
    'new_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartShippingLastName.php',
  ),
  'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartUrl' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartUrl',
    'module' => 'automations',
    'public' => false,
    'old_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartUrl.php',
    'new_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartUrl.php',
  ),
  'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartShippingState' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartShippingState',
    'module' => 'automations',
    'public' => false,
    'old_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartShippingState.php',
    'new_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartShippingState.php',
  ),
  'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartBillingCity' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartBillingCity',
    'module' => 'automations',
    'public' => false,
    'old_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartBillingCity.php',
    'new_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartBillingCity.php',
  ),
  'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartId' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartId',
    'module' => 'automations',
    'public' => false,
    'old_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartId.php',
    'new_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartId.php',
  ),
  'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartBillingCountry' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartBillingCountry',
    'module' => 'automations',
    'public' => false,
    'old_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartBillingCountry.php',
    'new_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartBillingCountry.php',
  ),
  'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartBillingEmail' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartBillingEmail',
    'module' => 'automations',
    'public' => false,
    'old_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartBillingEmail.php',
    'new_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartBillingEmail.php',
  ),
  'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartBillingPhone' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartBillingPhone',
    'module' => 'automations',
    'public' => false,
    'old_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartBillingPhone.php',
    'new_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartBillingPhone.php',
  ),
  'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartShippingCountry' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartShippingCountry',
    'module' => 'automations',
    'public' => false,
    'old_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartShippingCountry.php',
    'new_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartShippingCountry.php',
  ),
  'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartShippingAddress1' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartShippingAddress1',
    'module' => 'automations',
    'public' => false,
    'old_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartShippingAddress1.php',
    'new_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartShippingAddress1.php',
  ),
  'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartShippingPhone' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartShippingPhone',
    'module' => 'automations',
    'public' => false,
    'old_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartShippingPhone.php',
    'new_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartShippingPhone.php',
  ),
  'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartShippingAddress2' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartShippingAddress2',
    'module' => 'automations',
    'public' => false,
    'old_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartShippingAddress2.php',
    'new_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartShippingAddress2.php',
  ),
  'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartBillingFirstName' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartBillingFirstName',
    'module' => 'automations',
    'public' => false,
    'old_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartBillingFirstName.php',
    'new_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartBillingFirstName.php',
  ),
  'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartShippingCity' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Modules\\Automations\\MergeTags\\Woocommerce\\AbandonedCart\\CartShippingCity',
    'module' => 'automations',
    'public' => false,
    'old_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartShippingCity.php',
    'new_path' => 'includes/Modules/Automations/MergeTags/Woocommerce/AbandonedCart/CartShippingCity.php',
  ),
  'DoubleScale\\Pro\\Pro\\Modules\\Automations\\Migrations\\AbandonedCartsTable' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Modules\\Automations\\Migrations\\AbandonedCartsTable',
    'module' => 'automations',
    'public' => false,
    'old_path' => 'includes/Modules/Automations/Migrations/AbandonedCartsTable.php',
    'new_path' => 'includes/Modules/Automations/Migrations/AbandonedCartsTable.php',
  ),
  'DoubleScale\\Pro\\Pro\\UserRoles\\Permissions' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\UserRoles\\Permissions',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/UserRoles/Permissions.php',
    'new_path' => 'includes/Core/UserRoles/Permissions.php',
  ),
  'DoubleScale\\Pro\\Pro\\UserRoles\\UserRoles' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\UserRoles\\UserRoles',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/UserRoles/UserRoles.php',
    'new_path' => 'includes/Core/UserRoles/UserRoles.php',
  ),
  'DoubleScale\\Pro\\Pro\\UserRoles\\LoginRedirect' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\UserRoles\\LoginRedirect',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/UserRoles/LoginRedirect.php',
    'new_path' => 'includes/Core/UserRoles/LoginRedirect.php',
  ),
  'DoubleScale\\Pro\\Pro\\SubscriptionManage\\SubscriptionManage' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\SubscriptionManage\\SubscriptionManage',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/SubscriptionManage/SubscriptionManage.php',
    'new_path' => 'includes/Core/SubscriptionManage/SubscriptionManage.php',
  ),
  'DoubleScale\\Pro\\Pro\\Database\\Install' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\Database\\Install',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Database/Install.php',
    'new_path' => 'includes/Core/Database/Install.php',
  ),
  'DoubleScale\\Pro\\Pro\\Constants\\MessageSourceTypes' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\Support\\Constants\\MessageSourceTypes',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Constants/MessageSourceTypes.php',
    'new_path' => 'includes/Core/Support/Constants/MessageSourceTypes.php',
  ),
  'DoubleScale\\Pro\\Pro\\Constants\\MetaWhatsappErrorCodes' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\Support\\Constants\\MetaWhatsappErrorCodes',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Constants/MetaWhatsappErrorCodes.php',
    'new_path' => 'includes/Core/Support/Constants/MetaWhatsappErrorCodes.php',
  ),
  'DoubleScale\\Pro\\Pro\\Constants\\TaskType' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\Support\\Constants\\TaskType',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Constants/TaskType.php',
    'new_path' => 'includes/Core/Support/Constants/TaskType.php',
  ),
  'DoubleScale\\Pro\\Pro\\Constants\\CampaignChannel' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\Support\\Constants\\CampaignChannel',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Constants/CampaignChannel.php',
    'new_path' => 'includes/Core/Support/Constants/CampaignChannel.php',
  ),
  'DoubleScale\\Pro\\Pro\\Constants\\ActivityTypes' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\Support\\Constants\\ActivityTypes',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Constants/ActivityTypes.php',
    'new_path' => 'includes/Core/Support/Constants/ActivityTypes.php',
  ),
  'DoubleScale\\Pro\\Pro\\Constants\\MessageDirection' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\Support\\Constants\\MessageDirection',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Constants/MessageDirection.php',
    'new_path' => 'includes/Core/Support/Constants/MessageDirection.php',
  ),
  'DoubleScale\\Pro\\Pro\\Constants\\TaskEntityType' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\Support\\Constants\\TaskEntityType',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Constants/TaskEntityType.php',
    'new_path' => 'includes/Core/Support/Constants/TaskEntityType.php',
  ),
  'DoubleScale\\Pro\\Pro\\Constants\\TaskPriority' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\Support\\Constants\\TaskPriority',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Constants/TaskPriority.php',
    'new_path' => 'includes/Core/Support/Constants/TaskPriority.php',
  ),
  'DoubleScale\\Pro\\Pro\\Constants\\OrderStatus' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\Support\\Constants\\OrderStatus',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Constants/OrderStatus.php',
    'new_path' => 'includes/Core/Support/Constants/OrderStatus.php',
  ),
  'DoubleScale\\Pro\\Pro\\Constants\\SubscriptionStatus' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\Support\\Constants\\SubscriptionStatus',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Constants/SubscriptionStatus.php',
    'new_path' => 'includes/Core/Support/Constants/SubscriptionStatus.php',
  ),
  'DoubleScale\\Pro\\Pro\\Constants\\TaskStatus' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\Support\\Constants\\TaskStatus',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Constants/TaskStatus.php',
    'new_path' => 'includes/Core/Support/Constants/TaskStatus.php',
  ),
  'DoubleScale\\Pro\\Pro\\Constants\\TrackingStatus' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\Support\\Constants\\TrackingStatus',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Constants/TrackingStatus.php',
    'new_path' => 'includes/Core/Support/Constants/TrackingStatus.php',
  ),
  'DoubleScale\\Pro\\Pro\\Site\\License' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Site\\License',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Site/License.php',
    'new_path' => 'includes/Site/License.php',
  ),
  'DoubleScale\\Pro\\Pro\\Site\\Store' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Site\\Store',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Site/Store.php',
    'new_path' => 'includes/Site/Store.php',
  ),
  'DoubleScale\\Pro\\Pro\\Site\\Updater' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Site\\Updater',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Site/Updater.php',
    'new_path' => 'includes/Site/Updater.php',
  ),
  'DoubleScale\\Pro\\Pro\\Site\\Site' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Site\\Site',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Site/Site.php',
    'new_path' => 'includes/Site/Site.php',
  ),
  'DoubleScale\\Pro\\Pro\\Addon\\Settings' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\Addon\\Settings',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Addon/Settings.php',
    'new_path' => 'includes/Core/Addon/Settings.php',
  ),
  'DoubleScale\\Pro\\Pro\\Addon\\Addon' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\Addon\\Addon',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Addon/Addon.php',
    'new_path' => 'includes/Core/Addon/Addon.php',
  ),
  'DoubleScale\\Pro\\Pro\\Traits\\WhatsappTemplatePreparation' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\Support\\Traits\\WhatsappTemplatePreparation',
    'module' => 'core',
    'public' => true,
    'old_path' => 'includes/Traits/WhatsappTemplatePreparation.php',
    'new_path' => 'includes/Core/Support/Traits/WhatsappTemplatePreparation.php',
  ),
  'DoubleScale\\Pro\\Pro\\Traits\\MessageProviderValidation' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\Support\\Traits\\MessageProviderValidation',
    'module' => 'core',
    'public' => true,
    'old_path' => 'includes/Traits/MessageProviderValidation.php',
    'new_path' => 'includes/Core/Support/Traits/MessageProviderValidation.php',
  ),
  'DoubleScale\\Pro\\Pro\\Settings' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\Settings\\Settings',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Settings.php',
    'new_path' => 'includes/Core/Settings/Settings.php',
  ),
  'DoubleScale\\Pro\\Pro\\Utils\\PhoneValidator' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\Support\\PhoneValidator',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Utils/PhoneValidator.php',
    'new_path' => 'includes/Core/Support/PhoneValidator.php',
  ),
  'DoubleScale\\Pro\\Pro\\Fields\\Types\\EmailField' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\CustomFields\\EmailField',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Fields/Types/EmailField.php',
    'new_path' => 'includes/Core/CustomFields/EmailField.php',
  ),
  'DoubleScale\\Pro\\Pro\\Fields\\Types\\RadioField' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\CustomFields\\RadioField',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Fields/Types/RadioField.php',
    'new_path' => 'includes/Core/CustomFields/RadioField.php',
  ),
  'DoubleScale\\Pro\\Pro\\Fields\\Types\\SelectField' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\CustomFields\\SelectField',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Fields/Types/SelectField.php',
    'new_path' => 'includes/Core/CustomFields/SelectField.php',
  ),
  'DoubleScale\\Pro\\Pro\\Fields\\Types\\DateField' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\CustomFields\\DateField',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Fields/Types/DateField.php',
    'new_path' => 'includes/Core/CustomFields/DateField.php',
  ),
  'DoubleScale\\Pro\\Pro\\Fields\\Types\\TextareaField' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\CustomFields\\TextareaField',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Fields/Types/TextareaField.php',
    'new_path' => 'includes/Core/CustomFields/TextareaField.php',
  ),
  'DoubleScale\\Pro\\Pro\\Fields\\Types\\NumberField' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\CustomFields\\NumberField',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Fields/Types/NumberField.php',
    'new_path' => 'includes/Core/CustomFields/NumberField.php',
  ),
  'DoubleScale\\Pro\\Pro\\Fields\\Types\\PhoneField' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\CustomFields\\PhoneField',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Fields/Types/PhoneField.php',
    'new_path' => 'includes/Core/CustomFields/PhoneField.php',
  ),
  'DoubleScale\\Pro\\Pro\\Fields\\Types\\CheckboxField' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\CustomFields\\CheckboxField',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Fields/Types/CheckboxField.php',
    'new_path' => 'includes/Core/CustomFields/CheckboxField.php',
  ),
  'DoubleScale\\Pro\\Pro\\Fields\\Types\\TextField' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\CustomFields\\TextField',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Fields/Types/TextField.php',
    'new_path' => 'includes/Core/CustomFields/TextField.php',
  ),
  'DoubleScale\\Pro\\Pro\\Fields\\Types\\UrlField' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\CustomFields\\UrlField',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Fields/Types/UrlField.php',
    'new_path' => 'includes/Core/CustomFields/UrlField.php',
  ),
  'DoubleScale\\Pro\\Pro\\Fields\\Types\\MultiselectField' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\CustomFields\\MultiselectField',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Fields/Types/MultiselectField.php',
    'new_path' => 'includes/Core/CustomFields/MultiselectField.php',
  ),
  'DoubleScale\\Pro\\Pro\\Fields\\ContactFields' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\CustomFields\\ContactFields',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Fields/ContactFields.php',
    'new_path' => 'includes/Core/CustomFields/ContactFields.php',
  ),
  'DoubleScale\\Pro\\Pro\\Utils' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Core\\Support\\Utils',
    'module' => 'core',
    'public' => false,
    'old_path' => 'includes/Utils.php',
    'new_path' => 'includes/Core/Support/Utils.php',
  ),
  'DoubleScale\\Pro\\Pro\\Admin\\AdminConfig' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Admin\\AdminConfig',
    'module' => 'admin',
    'public' => false,
    'old_path' => 'includes/Admin/AdminConfig.php',
    'new_path' => 'includes/Admin/AdminConfig.php',
  ),
  'DoubleScale\\Pro\\Pro\\Admin\\AdminScriptsLoader' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Admin\\AdminScriptsLoader',
    'module' => 'admin',
    'public' => false,
    'old_path' => 'includes/Admin/AdminScriptsLoader.php',
    'new_path' => 'includes/Admin/AdminScriptsLoader.php',
  ),
  'DoubleScale\\Pro\\Pro\\Admin\\Admin' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Admin\\Admin',
    'module' => 'admin',
    'public' => false,
    'old_path' => 'includes/Admin/Admin.php',
    'new_path' => 'includes/Admin/Admin.php',
  ),
  'DoubleScale\\Pro\\Pro\\Admin\\AdminLoader' => 
  array (
    'new' => 'DoubleScale\\Pro\\Pro\\Admin\\AdminLoader',
    'module' => 'admin',
    'public' => false,
    'old_path' => 'includes/Admin/AdminLoader.php',
    'new_path' => 'includes/Admin/AdminLoader.php',
  ),
);
